version: "3.4"

volumes:
  elasticsearch-data:
    name: mbt_es_data

networks:
  backend:

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    container_name: mbt-elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - backend
    expose:
      - "9200"


  kibana:
    container_name: mbt-kibana
    image: docker.elastic.co/kibana/kibana:7.13.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200 # address of elasticsearch docker container which kibana will connect
    ports:
      - 5601:5601
    depends_on:
      - elastic
    networks:
      - backend
        # kibana will start when elasticsearch has started
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: mbt-api
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - elastic
    env_file:
      - ./secrets/env-docker-prod
    expose:
      - "8000"

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mbt-www
    ports:
      - "3000:80"
    networks:
      - backend
    depends_on:
      - api
    expose:
      - "3000"
